### ISSUE TITLE
MPI error while using HYPRE.jl

### ISSUE THREAD

**Issue by yewalenikhil65** [fredrikekre/HYPRE.jl#15]
I am running some tutorial in HYPRE.jl documentation.. and results in following error! .. Can someone help me here ?

```julia
 # Preconditioner
       precond = HYPRE.BoomerAMG(; RelaxType = 6, CoarsenType = 6)
HYPRE.BoomerAMG(Ptr{HYPRE.LibHYPRE.hypre_Solver_struct} @0x00000000070fda20)

# Solver
       solver = HYPRE.PCG(; MaxIter = 1000, Tol = 1e-9, Precond = precond)
HYPRE.PCG(MPI.Comm(67108864), Ptr{HYPRE.LibHYPRE.hypre_Solver_struct} @0x00000000070df990, HYPRE.BoomerAMG(Ptr{HYPRE.LibHYPRE.hypre_Solver_struct} @0x00000000070fda20))

julia> x = solve(solver, A, b);
Attempting to use an MPI routine (internal_Comm_size) before initializing or after finalizing MPICH
```

this just re-starts the julia !

**Comment by fredrikekre** [comment]
Can you include:
1. Version of HYPRE.jl: `using Pkg; Pkg.status("HYPRE")`
2. Information about Julia version and OS: `versioninfo()`
3. The full code that you are running, perhaps with a small mock-matrix if your code to set that up is long.

**Comment by yewalenikhil65** [comment]
Hi @fredrikekre  Thanks it worked ! I was using latest versions of Julia 1.9.0 and HYPRE.jl v1.4.0

HYPRE.Init() helped !

Can you point me to how I can construct a way to do geometric multigrid using HYPRE.jl ?

**Comment by fredrikekre** [comment]
Great, closing then.

HYPRE.jl currently only wraps the IJ interface of hypre, but you can open a feature request here pointing to the specific functionality you want to use from julia.
